[tools]
awscli = { version = "latest", symlink_bins = "true" }
bat = "latest"
btop = "latest"
bun = "latest"
duckdb = "latest"
eza = "latest"
fastfetch = "latest"
fzf = "latest"
gemini-cli = "latest"
go = "latest"
node = "latest"
"npm:sfw" = "latest"
"npm:skills" = "latest"
pnpm = "latest"
pre-commit = "latest"
rust = "latest"
terraform = "latest"
tlrc = "latest"
uv = "latest"
